### ISSUE TITLE
No BreakPoint debugging

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-livereload#2]
I followed the instructions and got my webpart in the tester page like you showed.
I was expecting to be able to debug the same way as workbench.
Was it not one of the features?

Thanks anyway

**Comment by StfBauer** [comment]
@Ofer-Gal thanks for reaching out!

Have you added the following query string to the URL:

```
?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js
```

![Screenshot 2024-07-12 at 12 56 01](https://github.com/user-attachments/assets/358f7703-03d8-430c-a7a1-54fb2bfc3e1d)

Alternatively you can connect via the toolbar itself.

![Screenshot 2024-07-11 at 14 57 23](https://github.com/user-attachments/assets/09fd607f-fd8c-4136-a001-9e7706965686)

When the plugs are disconnected it means your are not in debug mode and won't hit any breakpoints. Does the cords look like this:

![image](https://github.com/user-attachments/assets/f171b5eb-1b21-4830-a8ee-54e2ba8f4906)

**Left:** Means you are not in debug mode
**Right:** Means you are connected in debug mode

When you click the button to connect - the browser should refresh and you should see the following popup.

![image](https://github.com/user-attachments/assets/05ae53fc-f09a-4a6b-b6c2-03d7b5a3a217)

Then you have to click on "Load debug script".

Alternatively you can check if your sessionStorage has the `spfx-debug` set with a value:
![image](https://github.com/user-attachments/assets/d392d295-9494-4fce-bf5b-92f17e4da55f)

Not used by the extension but that's the confirmation it loads all your sources from localhost.

Hope this helps.

**Comment by Ofer-Gal** [comment]
I connected via the toolbar, clicked on "Load Debug script" and it showed connected.
Where should I see this ""spfx-debug"? in  DEBUG CONSOLE?

**Comment by StfBauer** [comment]
You write in the console:

```sh
sesssionStorage

```

and you will see something like this:

![image](https://github.com/user-attachments/assets/ad56810e-9114-4b3a-98e3-a7d42d33d36d)

BTW. which browser are you using?

**Comment by Ofer-Gal** [comment]
I am using Edge beta , Edge and chrome.
I started a new 1.19.0 web part vanila, added a button, and it did stop at the onClick function. 🥳
So I am good now. 
When I enter sesssionStorage in the debug console.
I get:
"Uncaught ReferenceError ReferenceError: sesssionStorage is not defined
    at <anonymous> (repl:1:1)"
My main .tsx is a React.FC not a class. Maybe that is the issue?
Also could you guide me as to how to use it as full page? To I deeply first and use new page -> app -> select it ? it will use the deployed one no?

Thank you much

**Comment by StfBauer** [comment]
> I get: "Uncaught ReferenceError ReferenceError: sesssionStorage is not defined at (repl:1:1)" My main .tsx is a React.FC not a class. 

You got this error in your browsers conole?

**Add Full Page:**
1. Create a new page
2.  Select App
3. Create

Then you will find the App Customiszer at the very bottom of the page. Plug in the workbench and set it to connected.

![image](https://github.com/user-attachments/assets/5ca8d6d2-9db4-4457-86d5-89995a6eeb77)


Just tried this on site where I create the PnP Live Reloader.

**Comment by Ofer-Gal** [comment]
Thought the deployed version would be active but when I am connected, the source is.
![image](https://github.com/user-attachments/assets/ed958e90-5fd4-4e2e-811e-74c513f24336)
But I can break only on the browser code. OK.
I see in the browser's console few related errors.
```
VM687:1  Uncaught SyntaxError: Unexpected token 's', "setImmedia"... is not valid JSON
    at JSON.parse (<anonymous>)
    at i (resources:14:185)
    at parse (resources:14:93)
    at t.handle (resources:15:894)
    at resources:15:3283

VM8616:1  Uncaught (in promise) SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at l._storageChangeDispatcher (content.js:2:855976)
    at _storageChangeDispatcherCallback (content.js:2:855424)
```
and sesssionStorage says:
```
VM8735:1 Uncaught ReferenceError: sesssionStorage is not defined
    at <anonymous>:1:1
(anonymous) | @ | VM8735:1
```

And there is reload long time after I make changes.
So I don't know if it is working or not. 🤣

**Comment by StfBauer** [comment]
Well you will always only hit breakpoints in the browser anyways. The auto reloader does what it supposed to do reload once your build was finished.

However you can force a manual breakpoint in your code always with a debugger statement:

```ts
debugger;

```

When this code gets executed the debugger in the browser fires, which then even hit after the reload.
From you screenshots it's not quite sure what and where you try to use sessionStorage those are pretty uncommon error message.

![image](https://github.com/user-attachments/assets/91171f55-ec4c-4afe-904d-b7d4ca833ed8)

You would also be able to see the sessionStorage on the application tab in the browser.

![image](https://github.com/user-attachments/assets/4ba64f8a-5a66-48c4-b568-51fce10eb604)
