### ISSUE TITLE
`README.md`: broken link

### ISSUE THREAD

**Issue by 6gal6ler6** [pnp/sp-livereload#5]
The following link is broken in the [README.md](https://github.com/pnp/sp-livereload/blob/main/README.md) File.

![image](https://github.com/user-attachments/assets/e8b1f363-6b7b-4c7a-a11d-3d63a8f9cebc)

![image](https://github.com/user-attachments/assets/edd37f66-1bf2-4981-ae87-b028022efc84)

**Comment by StfBauer** [comment]
Thanks for the info it is fixed now.
